from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from io import BytesIO

class PDFService:
    def generate_portfolio(self, analysis_data: dict, mapping_data: dict):
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        # Custom Styles
        title_style = ParagraphStyle(
            'CustomTitle',
            parent=styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=TA_CENTER
        )
        subtitle_style = ParagraphStyle(
            'CustomSubtitle',
            parent=styles['Heading2'],
            fontSize=18,
            spaceAfter=12,
            textColor=colors.darkblue
        )
        
        # Header
        story.append(Paragraph("RefugeeConnect AI", title_style))
        story.append(Paragraph("Professional Portfolio & Credential Assessment", styles['Heading2']))
        story.append(Spacer(1, 12))
        story.append(Paragraph("This document generated by AI to support professional integration.", styles['Italic']))
        story.append(Spacer(1, 24))

        # 1. Extracted Credential Info
        story.append(Paragraph("1. Credential Analysis", subtitle_style))
        
        credential_data = [
            ["Document Type", analysis_data.get('document_type', 'N/A')],
            ["Institution", analysis_data.get('institution', 'N/A')],
            ["Country", analysis_data.get('country', 'N/A')],
            ["Extracted Text Snippet", analysis_data.get('extracted_text', '')[:100] + "..."]
        ]
        
        t = Table(credential_data, colWidths=[150, 350])
        t.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
            ('TEXTCOLOR', (0, 0), (0, -1), colors.black),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
            ('GRID', (0, 0), (-1, -1), 1, colors.black)
        ]))
        story.append(t)
        story.append(Spacer(1, 24))

        # 2. Curriculum Mapping
        story.append(Paragraph("2. Curriculum Equivalency Mapping", subtitle_style))
        
        score_percent = f"{mapping_data.get('equivalency_score', 0) * 100:.0f}%"
        
        mapping_table_data = [
            ["Target Equivalent", mapping_data.get('target_degree', 'N/A')],
            ["Equivalency Score", score_percent],
        ]
        
        t2 = Table(mapping_table_data, colWidths=[150, 350])
        t2.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (0, -1), colors.lightgrey),
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
             ('GRID', (0, 0), (-1, -1), 1, colors.black),
              ('BOTTOMPADDING', (0, 0), (-1, -1), 12),
        ]))
        story.append(t2)
        story.append(Spacer(1, 12))

        # Gaps
        story.append(Paragraph("Identified Gaps:", styles['Heading3']))
        gaps = mapping_data.get('missing_modules', [])
        if gaps:
            for gap in gaps:
                story.append(Paragraph(f"• {gap}", styles['Normal']))
        else:
            story.append(Paragraph("No significant gaps identified.", styles['Normal']))

        story.append(Spacer(1, 12))

        # Recommendations
        story.append(Paragraph("Recommendations:", styles['Heading3']))
        recs = mapping_data.get('recommendations', [])
        if recs:
            for rec in recs:
                story.append(Paragraph(f"• {rec}", styles['Normal']))
        else:
             story.append(Paragraph("No specific recommendations.", styles['Normal']))

        doc.build(story)
        buffer.seek(0)
        return buffer

pdf_service = PDFService()
